version: "3.8"

services:
  redis:
    image: redis:5.0.9-alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
  gateway_server:
    container_name: gateway_server
    restart: always
    build:
      context: ./gateway-server
    ports:
      - 4005:4005
      - 4006:4006
      - 4007:4007
    volumes:
      - ./gateway-server:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - redis
    env_file:
      - ./gateway-server/.env
    command: yarn server
  subscriptions_server:
    container_name: subscriptions_server
    restart: always
    build:
      context: ./subscriptions-server
    ports:
      - 5001:5001
    volumes:
      - ./subscriptions-server:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - gateway_server
      - redis
    env_file:
      - ./subscriptions-server/.env
    command: yarn server
  react_app:
    container_name: react_app
    restart: always
    build:
      context: ./react-app
    volumes:
      - ./react-app:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./react-app/.env
    ports:
      - 3000:3000
    stdin_open: true
    command: npm start
